### ISSUE TITLE
Login Box

### ISSUE THREAD

**Issue by rowm30** [Shadow-Flash/CEDS#7]
- The login drop-down box is not working

- It is always redirecting the user to a separate page which can hinder the user cohesive experience

- Apply some UI tactics to increase UX.

Your Sincere Contributor 
💖💖

**Comment by Shadow-Flash** [comment]
> - The login drop-down box is not working
> 
> - It is always redirecting the user to a separate page which can hinder the user cohesive experience
> 
> - Apply some UI tactics to increase UX.
> 
> Your Sincere Contributor 
> 💖💖   

Yeah, I know I already Changed the whole login page check the live site.
